name: Maintain Repo
on: [push, pull_request]

jobs:
  maintain:
    runs-on: ubuntu-latest
    
    steps:
      - name: Format Code with Prettier
        uses: adhikareeprayush/Format-Code@v1.0
      
        
